-- SQL commands to run in Supabase SQL Editor

-- 1. First, create the users table (if not already created)
create table if not exists public.users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text not null,
  verified boolean not null default false,
  password text not null,
  extra json not null default '{}'::json,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email)
) TABLESPACE pg_default;

-- 2. Enable RLS but allow public access for authentication
alter table public.users enable row level security;

-- 3. Create policies for users table
create policy "Enable insert for public" on "public"."users"
  as permissive for insert
  to public
  with check (true);

create policy "Enable select for users based on user_id" on "public"."users"
  as permissive for select
  to public
  using (true);

create policy "Enable update for users based on user_id" on "public"."users"
  as permissive for update
  to public
  using (true);

-- 4. Update schools table policies if needed
alter table public.schools enable row level security;

create policy "Public can read schools" on public.schools 
  for select to public using (true);

create policy "Public can insert schools" on public.schools 
  for insert to public with check (true);

-- 5. Grant necessary permissions
grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
